import React, { useState, useRef, useMemo } from "react";
import { Upload, Sparkles, Image as ImageIcon, FileCode, Sliders, Palette, RefreshCcw } from "lucide-react";
import { THEME_PRESETS } from "./ThemePresets";
import { SVGProcessor, type ParsedSVG } from "./SVGProcessor";
import { ExportUtils } from "./ExportUtils";
import { ThemeEngine, type ThemeState } from "./ThemeEngine";

// Defaults
import { DEFAULT_BG_PATH, DEFAULT_LOGO_PATH, DEFAULT_VIEWBOX } from "./DefaultAssets";
import { ColorControl } from "./components/ColorControl";
import { EffectComposer } from "./components/EffectComposer"; // Updated Import

export const SVGLab = () => {
    // Core Data
    const [svgData, setSvgData] = useState<ParsedSVG | null>(null);
    const [isProcessing, setIsProcessing] = useState(false);

    // UX State
    const [mode, setMode] = useState<'presets' | 'edit'>('presets');
    const [activePresetId, setActivePresetId] = useState<string>("v1_kenichi_blue");

    // Theme State (Now uses Arrays of effects)
    const [themeState, setThemeState] = useState<ThemeState>(ThemeEngine.hydrateFromPreset("v1_kenichi_blue"));

    // Refs
    const svgRef = useRef<SVGSVGElement>(null);

    // Sync Preset -> State when clicking presets
    const applyPreset = (id: string) => {
        setActivePresetId(id);
        setThemeState(ThemeEngine.hydrateFromPreset(id));
    };

    // Derived defs string
    const dynamicDefs = useMemo(() => ThemeEngine.generateDefs(themeState), [themeState]);

    const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;
        try {
            const data = await SVGProcessor.parse(file);
            setSvgData(data);
        } catch (err) {
            alert("Error parsing SVG: " + err);
        }
    };

    const handleExport = async (format: "png" | "svg", scale = 1) => {
        if (!svgRef.current) return;
        setIsProcessing(true);
        try {
            if (format === "svg") {
                const serializer = new XMLSerializer();
                const source = serializer.serializeToString(svgRef.current);
                const blob = new Blob([source], { type: "image/svg+xml" });
                ExportUtils.downloadBlob(blob, `kenichi_brand.svg`);
            } else {
                const blob = await ExportUtils.svgToPng(svgRef.current, svgData?.width || 1024, svgData?.height || 1024, scale);
                ExportUtils.downloadBlob(blob, `kenichi_brand_@${scale}x.png`);
            }
        } catch (err) {
            console.error(err);
            alert("Export failed");
        }
        setIsProcessing(false);
    };

    // Determine current geometry
    const currentBgPath = svgData?.bgPath || DEFAULT_BG_PATH;
    const currentLogoPath = svgData?.logoPath || DEFAULT_LOGO_PATH;
    const currentViewBox = svgData?.viewBox || DEFAULT_VIEWBOX;

    // Determine Fills based on state
    const getFill = (target: 'background' | 'mark') => {
        const s = target === 'background' ? themeState.background : themeState.mark;
        if (s.type === 'solid') return s.color;
        return target === 'background' ? 'url(#bg_grad)' : 'url(#mark_grad)';
    };

    // Get Active Filter ID (generated by engine based on active effects)
    const getFilterUrl = (target: 'bg' | 'mark') => {
        const effects = target === 'bg' ? themeState.background.effects : themeState.mark.effects;
        const active = effects.some(e => e.enabled);
        if (!active) return undefined;
        return `url(#${ThemeEngine.getFilterId(target, effects)})`;
    };

    return (
        <div className="flex flex-col-reverse lg:flex-row h-full min-h-screen lg:min-h-0 lg:max-h-screen lg:overflow-hidden bg-white dark:bg-app-bg text-slate-900 dark:text-white">

            {/* LEFT: Controls */}
            <div className="w-full lg:w-[400px] flex flex-col gap-6 shrink-0 p-6 lg:p-6 lg:pl-6 pt-0 lg:pt-6 overflow-y-visible lg:overflow-y-auto border-r border-transparent dark:border-app-border">

                {/* Header */}
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <h1 className="text-2xl font-bold flex items-center gap-2">
                            <Sparkles className="text-accent" /> SVG Lab <span className="text-[10px] bg-accent/20 text-accent px-2 py-0.5 rounded-full">v3</span>
                        </h1>
                        <div className="flex bg-slate-100 dark:bg-black rounded-lg p-1">
                            <button onClick={() => setMode('presets')} className={`p-2 rounded-md transition-all ${mode === 'presets' ? 'bg-white dark:bg-slate-800 shadow-sm text-accent' : 'text-slate-400 hover:text-slate-600'}`}>
                                <Palette size={18} />
                            </button>
                            <button onClick={() => setMode('edit')} className={`p-2 rounded-md transition-all ${mode === 'edit' ? 'bg-white dark:bg-slate-800 shadow-sm text-accent' : 'text-slate-400 hover:text-slate-600'}`}>
                                <Sliders size={18} />
                            </button>
                        </div>
                    </div>
                </div>

                {/* Main Interaction Area */}
                {mode === 'presets' ? (
                    <div className="space-y-4 animate-in fade-in slide-in-from-left-4 duration-300">
                        {/* Upload */}
                        <div className="p-4 border-2 border-dashed border-app-light-border dark:border-app-border rounded-xl text-center transition-colors hover:border-accent group">
                            <input
                                type="file"
                                accept=".svg"
                                className="hidden"
                                id="svg-upload"
                                onChange={handleFileUpload}
                            />
                            <label htmlFor="svg-upload" className="cursor-pointer flex flex-col items-center gap-2 group-hover:text-accent transition-colors">
                                <Upload size={24} className="text-slate-400 group-hover:text-accent" />
                                <span className="text-sm font-medium">Upload Master SVG</span>
                                <span className="text-xs text-slate-400">Drag & Drop or Click</span>
                            </label>
                        </div>

                        {/* Presets Grid */}
                        <div className="space-y-3">
                            <h3 className="text-xs font-bold uppercase text-slate-400">Global Presets</h3>
                            <div className="grid grid-cols-1 gap-2">
                                {THEME_PRESETS.map(theme => (
                                    <button
                                        key={theme.id}
                                        onClick={() => applyPreset(theme.id)}
                                        className={`flex items-center gap-3 p-3 rounded-xl transition-all text-left border ${activePresetId === theme.id
                                            ? "bg-accent/10 border-accent dark:border-accent text-accent"
                                            : "bg-app-light-surface dark:bg-app-surface border-transparent hover:bg-app-light-surface-hover dark:hover:bg-app-surface-hover"
                                            }`}
                                    >
                                        <div className="w-8 h-8 rounded-full shadow-sm shrink-0 overflow-hidden relative">
                                            <div className="absolute inset-0" style={{ background: theme.bgFill.includes('url') ? `linear-gradient(135deg, ${theme.id === 'v1_kenichi_blue' ? '#3B82F6, #1D4ED8' : '#FECaca, #DC2626'})` : theme.bgFill }}></div>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <div className="font-bold text-sm truncate">{theme.name}</div>
                                            <div className="text-[10px] opacity-70 truncate">{theme.description}</div>
                                        </div>
                                    </button>
                                ))}
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                        {/* Edit Mode Controls */}

                        {/* Background Section */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-bold flex items-center gap-2 pb-2 border-b border-slate-100 dark:border-slate-800">
                                <div className="w-3 h-3 rounded-full bg-slate-400"></div> Background
                            </h3>

                            <ColorControl
                                label="Fill Style"
                                type={themeState.background.type}
                                color={themeState.background.color}
                                gradientStart={themeState.background.gradientStart}
                                gradientEnd={themeState.background.gradientEnd}
                                onTypeChange={(t) => setThemeState(s => ({ ...s, background: { ...s.background, type: t } }))}
                                onColorChange={(c) => setThemeState(s => ({ ...s, background: { ...s.background, color: c } }))}
                                onGradientStartChange={(c) => setThemeState(s => ({ ...s, background: { ...s.background, gradientStart: c } }))}
                                onGradientEndChange={(c) => setThemeState(s => ({ ...s, background: { ...s.background, gradientEnd: c } }))}
                            />

                            {/* Border Radius Control */}
                            <div className="space-y-1">
                                <div className="flex justify-between">
                                    <label className="text-[10px] text-slate-400 font-bold uppercase">Corner Radius</label>
                                    <span className="text-[10px] font-mono opacity-50">{Math.round(themeState.background.borderRadius * 100)}%</span>
                                </div>
                                <input
                                    type="range" min="0" max="0.5" step="0.05"
                                    value={themeState.background.borderRadius}
                                    onChange={(e) => setThemeState(s => ({ ...s, background: { ...s.background, borderRadius: parseFloat(e.target.value) } }))}
                                    className="w-full h-1 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-accent"
                                />
                            </div>

                            <EffectComposer
                                label="Effects Stack"
                                effects={themeState.background.effects}
                                onChange={(effects) => setThemeState(s => ({ ...s, background: { ...s.background, effects } }))}
                            />
                        </div>

                        {/* Mark Section */}
                        <div className="space-y-4">
                            <h3 className="text-sm font-bold flex items-center gap-2 pb-2 border-b border-slate-100 dark:border-slate-800">
                                <div className="w-3 h-3 rounded-full bg-accent"></div> Brand Mark
                            </h3>

                            <ColorControl
                                label="Fill Style"
                                type={themeState.mark.type}
                                color={themeState.mark.color}
                                gradientStart={themeState.mark.gradientStart}
                                gradientEnd={themeState.mark.gradientEnd}
                                onTypeChange={(t) => setThemeState(s => ({ ...s, mark: { ...s.mark, type: t } }))}
                                onColorChange={(c) => setThemeState(s => ({ ...s, mark: { ...s.mark, color: c } }))}
                                onGradientStartChange={(c) => setThemeState(s => ({ ...s, mark: { ...s.mark, gradientStart: c } }))}
                                onGradientEndChange={(c) => setThemeState(s => ({ ...s, mark: { ...s.mark, gradientEnd: c } }))}
                            />

                            <EffectComposer
                                label="Effects Stack"
                                effects={themeState.mark.effects}
                                onChange={(effects) => setThemeState(s => ({ ...s, mark: { ...s.mark, effects } }))}
                            />
                        </div>

                        <button
                            onClick={() => setThemeState(ThemeEngine.hydrateFromPreset("v1_kenichi_blue"))}
                            className="w-full py-2 flex items-center justify-center gap-2 text-xs font-bold text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
                        >
                            <RefreshCcw size={12} /> Reset to Default
                        </button>
                    </div>
                )}


                <div className="mt-auto space-y-2 pt-6 border-t border-app-light-border dark:border-app-border pb-6 lg:pb-0">
                    <h3 className="text-xs font-bold uppercase text-slate-400">Export Asset</h3>
                    <div className="grid grid-cols-2 gap-2">
                        <button
                            disabled={isProcessing}
                            onClick={() => handleExport("svg")}
                            className="flex items-center justify-center gap-2 p-3 bg-app-light-surface dark:bg-app-surface rounded-lg font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                        >
                            <FileCode size={16} /> SVG
                        </button>
                        <div className="flex bg-indigo-600 rounded-lg overflow-hidden">
                            <button
                                disabled={isProcessing}
                                onClick={() => handleExport("png", 1)}
                                className="flex-1 flex items-center justify-center gap-2 p-3 text-white font-bold text-sm hover:bg-indigo-700 transition-colors border-r border-indigo-700"
                            >
                                <ImageIcon size={16} /> PNG
                            </button>
                            <button
                                disabled={isProcessing}
                                onClick={() => handleExport("png", 2)}
                                className="px-3 text-white font-bold text-xs hover:bg-indigo-700 transition-colors border-r border-indigo-700"
                                title="Export @2x (2048px)"
                            >
                                2x
                            </button>
                            <button
                                disabled={isProcessing}
                                onClick={() => handleExport("png", 4)}
                                className="px-3 text-white font-bold text-xs hover:bg-indigo-700 transition-colors"
                                title="Export @4x (4096px)"
                            >
                                4x
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            {/* RIGHT: Preview */}
            <div className="flex-1 bg-slate-50 dark:bg-[#0c0c0e] rounded-b-3xl lg:rounded-3xl flex items-center justify-center p-6 lg:p-10 relative overflow-hidden min-h-[400px] lg:min-h-0 lg:m-6 shadow-inner lg:shadow-none transition-colors duration-500">
                <div className="absolute inset-0 opacity-5 dark:opacity-20 pointer-events-none"
                    style={{ backgroundImage: "radial-gradient(circle at 1px 1px, #71717a 1px, transparent 0)", backgroundSize: "24px 24px" }}>
                </div>

                <div className="relative shadow-2xl rounded-[24%] overflow-hidden w-full max-w-[600px] aspect-square bg-transparent transition-all duration-500 ring-1 ring-black/5 dark:ring-white/10">
                    <svg
                        ref={svgRef}
                        viewBox={currentViewBox}
                        className="w-full h-full block"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <defs dangerouslySetInnerHTML={{ __html: dynamicDefs }} />

                        {/* Background */}
                        {/* Background */}
                        <g filter={getFilterUrl('bg')}>
                            <path
                                d={currentBgPath}
                                fill={getFill('background')}
                                clipPath={themeState.background.borderRadius > 0 ? "url(#bg_clip)" : undefined}
                            />
                        </g>

                        {/* Logo Mark */}
                        <g filter={getFilterUrl('mark')}>
                            <path d={currentLogoPath} fill={getFill('mark')} />
                        </g>
                    </svg>
                </div>
            </div>
        </div>
    );
};
